package push

import "testing"

// TestSignByteExactness pins Go's sign()+marshalPayload() output against a
// golden fixture computed once from the REAL server-side algorithm
// (core-service's factory/log.js validateSignature, confirmed byte-identical
// to the matching client in open-source/sdk/logstyx-js-node). The fixture was
// generated by running the exact destructure-rebuild-stringify-HMAC sequence
// in node (see the gen_fixture.js used to produce this), not re-derived here,
// so this test catches any future drift in marshalPayload/sign from that
// contract - especially the HTML-escaping and field-order pitfalls, which is
// why the payload below deliberately includes '<', '>', '&' in pushed lines
// and a multi-key context/device.
func TestSignByteExactness(t *testing.T) {
	const (
		secret    = "test-secret-DO-NOT-USE-IN-PROD"
		projectID = "proj_test_12345"
		tsMillis  = 1700000000000

		// Computed by running the real server algorithm in node against the
		// logical payload below (device/context keys listed in the same
		// alphabetical order Go's encoding/json produces for map[string]string,
		// so the two implementations' JSON text lines up byte-for-byte).
		wantParams = `{"level":"error","projectId":"proj_test_12345","device":{"hostname":"test-host","platform":"linux","type":"probestyx"},"context":{"environment":"production","region":"us-east-1"},"data":{"scraper":"nginx_errors","count":2,"lines":["GET /a?x=1&y=2 -> 404","<script>alert(1)</script> blocked"]}}`
		wantSignature = "CE44811ED421E784C5588B39E5C19AAB7DCE1D02BE390877E21CA0FE4086AFFC"
	)

	payload := &logPayload{
		Level:     "error",
		ProjectID: projectID,
		Device: map[string]string{
			"type":     "probestyx",
			"hostname": "test-host",
			"platform": "linux",
		},
		Context: map[string]string{
			"environment": "production",
			"region":      "us-east-1",
		},
		Data: logData{
			Scraper: "nginx_errors",
			Count:   2,
			Lines: []string{
				"GET /a?x=1&y=2 -> 404",
				"<script>alert(1)</script> blocked",
			},
		},
	}

	body, err := marshalPayload(payload)
	if err != nil {
		t.Fatalf("marshalPayload: %v", err)
	}
	if string(body) != wantParams {
		t.Fatalf("marshalPayload byte mismatch:\n got: %s\nwant: %s", body, wantParams)
	}

	got := sign(secret, projectID, body, tsMillis)
	if got != wantSignature {
		t.Fatalf("sign mismatch:\n got: %s\nwant: %s", got, wantSignature)
	}
}

// TestSignByteExactness_NoEscaping guards specifically against a regression to
// Go's default HTML-escaping (json.Marshal escapes < > & by default; the
// server's JSON.stringify does not) reappearing in marshalPayload.
func TestSignByteExactness_NoEscaping(t *testing.T) {
	payload := &logPayload{
		Level:     "error",
		ProjectID: "p",
		Device:    map[string]string{},
		Context:   map[string]string{},
		Data: logData{
			Scraper: "s",
			Count:   1,
			Lines:   []string{"<a href=\"x\">y</a> & more"},
		},
	}
	body, err := marshalPayload(payload)
	if err != nil {
		t.Fatalf("marshalPayload: %v", err)
	}
	const want = `{"level":"error","projectId":"p","device":{},"context":{},"data":{"scraper":"s","count":1,"lines":["<a href=\"x\">y</a> & more"]}}`
	if string(body) != want {
		t.Fatalf("HTML-escaping regression:\n got: %s\nwant: %s", body, want)
	}
}
